FROM python:3.9-slim-buster

ENV LANG=C.UTF-8 \
  LC_ALL=C.UTF-8 \
  PATH="${PATH}:/root/.poetry/bin"

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    curl \
    git \
    make \
    graphviz \
  && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

COPY poetry.lock pyproject.toml ./

RUN /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
RUN steampipe plugin install aws


WORKDIR /usr/src/pacu
RUN useradd -m -s /bin/bash pacu

ENV PATH "/opt/poetry/venv/bin:${PATH}"
ENV VIRTUAL_ENV "/opt/poetry/venv"
RUN mkdir -p "$VIRTUAL_ENV" \
        && chown -R pacu:pacu "$VIRTUAL_ENV"

USER pacu

RUN poetry install --no-root


RUN echo "export PATH=/opt/poetry/venv/bin:${PATH}" >> /home/pacu/.profile && \
    echo "export VIRTUAL_ENV=/opt/poetry/venv" >> /home/pacu/.profile


#COPY . .

CMD ["bash", "-l"]
#CMD ["python", "-m", "pacu"]
