site_name: pacu
site_description: The AWS exploitation framework, designed for testing the security of Amazon Web Services environments.
site_author: Ryan Gerstenkorn

repo_url: https://github.com/RyanJarv/pacu
edit_uri: https://github.com/RyanJarv/pacu/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
