# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2021-12-31T02:46:18+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, List, Optional

from pydantic import BaseModel, Extra, Field


class AccessDeniedException(BaseModel):
    __root__: Any


class ConflictException(AccessDeniedException):
    pass


class InternalServerException(AccessDeniedException):
    pass


class ResourceNotFoundException(AccessDeniedException):
    pass


class ServiceQuotaExceededException(AccessDeniedException):
    pass


class ThrottlingException(AccessDeniedException):
    pass


class ValidationException(AccessDeniedException):
    pass


class PackageVersion(BaseModel):
    __root__: Annotated[str, Field(max_length=255, min_length=1, regex='[^!#/\\s]+')]


class PackageVersionRevision(BaseModel):
    __root__: Annotated[str, Field(max_length=50, min_length=1, regex='\\S+')]


class TagResourceResult(BaseModel):
    pass


class UntagResourceResult(TagResourceResult):
    pass


class TagKey(BaseModel):
    __root__: Annotated[str, Field(max_length=128, min_length=1)]


class AccountId(BaseModel):
    __root__: Annotated[str, Field(max_length=12, min_length=12, regex='[0-9]{12}')]


class Arn(BaseModel):
    __root__: Annotated[str, Field(max_length=1011, min_length=1, regex='\\S+')]


class Asset(BaseModel):
    __root__: str


class HashValue(BaseModel):
    __root__: Annotated[str, Field(max_length=512, min_length=32, regex='[0-9a-f]+')]


class AssetHashes(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class AssetName(BaseModel):
    __root__: Annotated[str, Field(max_length=255, min_length=1, regex='\\P{C}+')]


class LongOptional(BaseModel):
    __root__: int


class AssetSummary(BaseModel):
    """
    Contains details about a package version asset.
    """

    name: AssetName
    size: Optional[LongOptional] = None
    hashes: Optional[AssetHashes] = None


class AssetSummaryList(BaseModel):
    __root__: List[AssetSummary]


class DomainName(BaseModel):
    __root__: Annotated[
        str, Field(max_length=50, min_length=2, regex='[a-z][a-z0-9\\-]{0,48}[a-z0-9]')
    ]


class RepositoryName(BaseModel):
    __root__: Annotated[
        str,
        Field(max_length=100, min_length=2, regex='[A-Za-z0-9][A-Za-z0-9._\\-]{1,99}'),
    ]


class ExternalConnectionName(BaseModel):
    __root__: Annotated[str, Field(regex='[A-Za-z0-9][A-Za-z0-9._\\-:]{1,99}')]


class AssociateExternalConnectionRequest(BaseModel):
    pass


class AuthorizationTokenDurationSeconds(BaseModel):
    __root__: Annotated[int, Field(ge=0.0, le=43200.0)]


class BooleanOptional(BaseModel):
    __root__: bool


class PackageFormat(Enum):
    npm = 'npm'
    pypi = 'pypi'
    maven = 'maven'
    nuget = 'nuget'


class PackageNamespace(PackageVersion):
    pass


class PackageName(PackageVersion):
    pass


class PackageVersionList(BaseModel):
    __root__: Annotated[List[PackageVersion], Field(max_items=100)]


class PackageVersionRevisionMap(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class CopyPackageVersionsRequest(BaseModel):
    versions: Optional[PackageVersionList] = None
    versionRevisions: Optional[PackageVersionRevisionMap] = None
    allowOverwrite: Optional[BooleanOptional] = None
    includeFromUpstream: Optional[BooleanOptional] = None


class SuccessfulPackageVersionInfoMap(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class PackageVersionErrorMap(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class Description(BaseModel):
    __root__: Annotated[str, Field(max_length=1000, regex='\\P{C}+')]


class PolicyRevision(BaseModel):
    __root__: Annotated[str, Field(max_length=100, min_length=1, regex='\\S+')]


class DeleteDomainPermissionsPolicyRequest(BaseModel):
    pass


class DeleteDomainRequest(BaseModel):
    pass


class PackageVersionStatus(Enum):
    Published = 'Published'
    Unfinished = 'Unfinished'
    Unlisted = 'Unlisted'
    Archived = 'Archived'
    Disposed = 'Disposed'
    Deleted = 'Deleted'


class DeletePackageVersionsRequest(BaseModel):
    versions: PackageVersionList
    expectedStatus: Optional[PackageVersionStatus] = None


class DeleteRepositoryPermissionsPolicyRequest(BaseModel):
    pass


class DeleteRepositoryRequest(BaseModel):
    pass


class DescribeDomainRequest(BaseModel):
    pass


class DescribePackageVersionRequest(BaseModel):
    pass


class DescribeRepositoryRequest(BaseModel):
    pass


class DisassociateExternalConnectionRequest(BaseModel):
    pass


class DisposePackageVersionsRequest(BaseModel):
    versions: PackageVersionList
    versionRevisions: Optional[PackageVersionRevisionMap] = None
    expectedStatus: Optional[PackageVersionStatus] = None


class DomainStatus(Enum):
    Active = 'Active'
    Deleted = 'Deleted'


class Timestamp(BaseModel):
    __root__: datetime


class Integer(LongOptional):
    pass


class Long(LongOptional):
    pass


class DomainSummary(BaseModel):
    """
    Information about a domain, including its name, Amazon Resource Name (ARN), and status. The <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_ListDomains.html">ListDomains</a> operation returns a list of <code>DomainSummary</code> objects.
    """

    name: Optional[DomainName] = None
    owner: Optional[AccountId] = None
    arn: Optional[Arn] = None
    status: Optional[DomainStatus] = None
    createdTime: Optional[Timestamp] = None
    encryptionKey: Optional[Arn] = None


class DomainSummaryList(BaseModel):
    __root__: List[DomainSummary]


class ErrorMessage(Asset):
    pass


class ExternalConnectionStatus(Enum):
    Available = 'Available'


class GetAuthorizationTokenRequest(BaseModel):
    pass


class String(Asset):
    pass


class GetDomainPermissionsPolicyRequest(BaseModel):
    pass


class GetPackageVersionAssetRequest(BaseModel):
    pass


class GetPackageVersionReadmeRequest(BaseModel):
    pass


class GetRepositoryEndpointRequest(BaseModel):
    pass


class GetRepositoryPermissionsPolicyRequest(BaseModel):
    pass


class HashAlgorithm(Enum):
    MD5 = 'MD5'
    SHA_1 = 'SHA-1'
    SHA_256 = 'SHA-256'
    SHA_512 = 'SHA-512'


class LicenseInfo(BaseModel):
    """
    Details of the license data.
    """

    name: Optional[String] = None
    url: Optional[String] = None


class LicenseInfoList(BaseModel):
    __root__: List[LicenseInfo]


class ListDomainsMaxResults(BaseModel):
    __root__: Annotated[int, Field(ge=1.0, le=1000.0)]


class PaginationToken(BaseModel):
    __root__: Annotated[str, Field(max_length=2000, min_length=1, regex='\\S+')]


class ListDomainsRequest(BaseModel):
    maxResults: Optional[ListDomainsMaxResults] = None
    nextToken: Optional[PaginationToken] = None


class ListPackageVersionAssetsMaxResults(ListDomainsMaxResults):
    pass


class ListPackageVersionAssetsRequest(BaseModel):
    pass


class ListPackageVersionDependenciesRequest(BaseModel):
    pass


class ListPackageVersionsMaxResults(ListDomainsMaxResults):
    pass


class PackageVersionSortType(Enum):
    PUBLISHED_TIME = 'PUBLISHED_TIME'


class ListPackageVersionsRequest(BaseModel):
    pass


class ListPackagesMaxResults(ListDomainsMaxResults):
    pass


class ListPackagesRequest(BaseModel):
    pass


class ListRepositoriesInDomainMaxResults(ListDomainsMaxResults):
    pass


class ListRepositoriesInDomainRequest(BaseModel):
    pass


class ListRepositoriesMaxResults(ListDomainsMaxResults):
    pass


class ListRepositoriesRequest(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class PackageDependency(BaseModel):
    """
    Details about a package dependency.
    """

    namespace: Optional[PackageNamespace] = None
    package: Optional[PackageName] = None
    dependencyType: Optional[String] = None
    versionRequirement: Optional[String] = None


class PackageSummary(BaseModel):
    """
    Details about a package, including its format, namespace, and name. The <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_ListPackages.html">ListPackages</a> operation returns a list of <code>PackageSummary</code> objects.
    """

    format: Optional[PackageFormat] = None
    namespace: Optional[PackageNamespace] = None
    package: Optional[PackageName] = None


class String255(BaseModel):
    __root__: Annotated[str, Field(max_length=255, min_length=1)]


class PackageVersionErrorCode(Enum):
    ALREADY_EXISTS = 'ALREADY_EXISTS'
    MISMATCHED_REVISION = 'MISMATCHED_REVISION'
    MISMATCHED_STATUS = 'MISMATCHED_STATUS'
    NOT_ALLOWED = 'NOT_ALLOWED'
    NOT_FOUND = 'NOT_FOUND'
    SKIPPED = 'SKIPPED'


class PackageVersionError(BaseModel):
    """
    An error associated with package.
    """

    errorCode: Optional[PackageVersionErrorCode] = None
    errorMessage: Optional[ErrorMessage] = None


class PackageVersionSummary(BaseModel):
    """
    Details about a package version, including its status, version, and revision. The <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_ListPackageVersions.html">ListPackageVersions</a> operation returns a list of <code>PackageVersionSummary</code> objects.
    """

    version: PackageVersion
    revision: Optional[PackageVersionRevision] = None
    status: PackageVersionStatus


class PolicyDocument(BaseModel):
    __root__: Annotated[str, Field(max_length=5120, min_length=1)]


class PutDomainPermissionsPolicyRequest(BaseModel):
    domain: DomainName
    domainOwner: Optional[AccountId] = None
    policyRevision: Optional[PolicyRevision] = None
    policyDocument: PolicyDocument


class PutRepositoryPermissionsPolicyRequest(BaseModel):
    policyRevision: Optional[PolicyRevision] = None
    policyDocument: PolicyDocument


class RepositoryExternalConnectionInfo(BaseModel):
    """
    Contains information about the external connection of a repository.
    """

    externalConnectionName: Optional[ExternalConnectionName] = None
    packageFormat: Optional[PackageFormat] = None
    status: Optional[ExternalConnectionStatus] = None


class RepositorySummary(BaseModel):
    """
    Details about a repository, including its Amazon Resource Name (ARN), description, and domain information. The <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_ListRepositories.html">ListRepositories</a> operation returns a list of <code>RepositorySummary</code> objects.
    """

    name: Optional[RepositoryName] = None
    administratorAccount: Optional[AccountId] = None
    domainName: Optional[DomainName] = None
    domainOwner: Optional[AccountId] = None
    arn: Optional[Arn] = None
    description: Optional[Description] = None


class SuccessfulPackageVersionInfo(BaseModel):
    """
    Contains the revision and status of a package version.
    """

    revision: Optional[String] = None
    status: Optional[PackageVersionStatus] = None


class TagValue(BaseModel):
    __root__: Annotated[str, Field(max_length=256, min_length=0)]


class TagKeyList(BaseModel):
    __root__: Annotated[List[TagKey], Field(max_items=200, min_items=0)]


class UntagResourceRequest(BaseModel):
    tagKeys: TagKeyList


class UpdatePackageVersionsStatusRequest(BaseModel):
    versions: PackageVersionList
    versionRevisions: Optional[PackageVersionRevisionMap] = None
    expectedStatus: Optional[PackageVersionStatus] = None
    targetStatus: PackageVersionStatus


class UpstreamRepositoryInfo(BaseModel):
    """
    Information about an upstream repository.
    """

    repositoryName: Optional[RepositoryName] = None


class CopyPackageVersionsResult(BaseModel):
    successfulVersions: Optional[SuccessfulPackageVersionInfoMap] = None
    failedVersions: Optional[PackageVersionErrorMap] = None


class Tag(BaseModel):
    """
    A tag is a key-value pair that can be used to manage, search for, or filter resources in AWS CodeArtifact.
    """

    key: TagKey
    value: TagValue


class UpstreamRepository(BaseModel):
    """
    Information about an upstream repository. A list of <code>UpstreamRepository</code> objects is an input parameter to <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_CreateRepository.html">CreateRepository</a> and <a href="https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_UpdateRepository.html">UpdateRepository</a>.
    """

    repositoryName: RepositoryName


class DeletePackageVersionsResult(CopyPackageVersionsResult):
    pass


class DisposePackageVersionsResult(CopyPackageVersionsResult):
    pass


class GetAuthorizationTokenResult(BaseModel):
    authorizationToken: Optional[String] = None
    expiration: Optional[Timestamp] = None


class GetPackageVersionAssetResult(BaseModel):
    asset: Optional[Asset] = None


class GetPackageVersionReadmeResult(BaseModel):
    format: Optional[PackageFormat] = None
    namespace: Optional[PackageNamespace] = None
    package: Optional[PackageName] = None
    version: Optional[PackageVersion] = None
    versionRevision: Optional[PackageVersionRevision] = None
    readme: Optional[String] = None


class GetRepositoryEndpointResult(BaseModel):
    repositoryEndpoint: Optional[String] = None


class ListDomainsResult(BaseModel):
    domains: Optional[DomainSummaryList] = None
    nextToken: Optional[PaginationToken] = None


class ListPackageVersionAssetsResult(BaseModel):
    format: Optional[PackageFormat] = None
    namespace: Optional[PackageNamespace] = None
    package: Optional[PackageName] = None
    version: Optional[PackageVersion] = None
    versionRevision: Optional[PackageVersionRevision] = None
    nextToken: Optional[PaginationToken] = None
    assets: Optional[AssetSummaryList] = None


class UpdatePackageVersionsStatusResult(CopyPackageVersionsResult):
    pass


class TagList(BaseModel):
    __root__: Annotated[List[Tag], Field(max_items=200, min_items=0)]


class CreateDomainRequest(BaseModel):
    encryptionKey: Optional[Arn] = None
    tags: Optional[TagList] = None


class DomainDescription(BaseModel):
    """
    Information about a domain. A domain is a container for repositories. When you create a domain, it is empty until you add one or more repositories.
    """

    name: Optional[DomainName] = None
    owner: Optional[AccountId] = None
    arn: Optional[Arn] = None
    status: Optional[DomainStatus] = None
    createdTime: Optional[Timestamp] = None
    encryptionKey: Optional[Arn] = None
    repositoryCount: Optional[Integer] = None
    assetSizeBytes: Optional[Long] = None
    s3BucketArn: Optional[Arn] = None


class UpstreamRepositoryList(BaseModel):
    __root__: List[UpstreamRepository]


class CreateRepositoryRequest(BaseModel):
    description: Optional[Description] = None
    upstreams: Optional[UpstreamRepositoryList] = None
    tags: Optional[TagList] = None


class ResourcePolicy(BaseModel):
    """
    An AWS CodeArtifact resource policy that contains a resource ARN, document details, and a revision.
    """

    resourceArn: Optional[Arn] = None
    revision: Optional[PolicyRevision] = None
    document: Optional[PolicyDocument] = None


class PackageVersionDescription(BaseModel):
    """
    Details about a package version.
    """

    format: Optional[PackageFormat] = None
    namespace: Optional[PackageNamespace] = None
    packageName: Optional[PackageName] = None
    displayName: Optional[String255] = None
    version: Optional[PackageVersion] = None
    summary: Optional[String] = None
    homePage: Optional[String] = None
    sourceCodeRepository: Optional[String] = None
    publishedTime: Optional[Timestamp] = None
    licenses: Optional[LicenseInfoList] = None
    revision: Optional[PackageVersionRevision] = None
    status: Optional[PackageVersionStatus] = None


class PackageDependencyList(BaseModel):
    __root__: List[PackageDependency]


class PackageVersionSummaryList(BaseModel):
    __root__: List[PackageVersionSummary]


class PackageSummaryList(BaseModel):
    __root__: List[PackageSummary]


class RepositorySummaryList(BaseModel):
    __root__: List[RepositorySummary]


class UpstreamRepositoryInfoList(BaseModel):
    __root__: List[UpstreamRepositoryInfo]


class RepositoryExternalConnectionInfoList(BaseModel):
    __root__: List[RepositoryExternalConnectionInfo]


class TagResourceRequest(BaseModel):
    tags: TagList


class UpdateRepositoryRequest(BaseModel):
    description: Optional[Description] = None
    upstreams: Optional[UpstreamRepositoryList] = None


class CreateDomainResult(BaseModel):
    domain: Optional[DomainDescription] = None


class DeleteDomainResult(CreateDomainResult):
    pass


class DeleteDomainPermissionsPolicyResult(BaseModel):
    policy: Optional[ResourcePolicy] = None


class DeleteRepositoryPermissionsPolicyResult(DeleteDomainPermissionsPolicyResult):
    pass


class DescribeDomainResult(CreateDomainResult):
    pass


class DescribePackageVersionResult(BaseModel):
    packageVersion: PackageVersionDescription


class GetDomainPermissionsPolicyResult(DeleteDomainPermissionsPolicyResult):
    pass


class GetRepositoryPermissionsPolicyResult(DeleteDomainPermissionsPolicyResult):
    pass


class ListPackageVersionDependenciesResult(BaseModel):
    format: Optional[PackageFormat] = None
    namespace: Optional[PackageNamespace] = None
    package: Optional[PackageName] = None
    version: Optional[PackageVersion] = None
    versionRevision: Optional[PackageVersionRevision] = None
    nextToken: Optional[PaginationToken] = None
    dependencies: Optional[PackageDependencyList] = None


class ListPackageVersionsResult(BaseModel):
    defaultDisplayVersion: Optional[PackageVersion] = None
    format: Optional[PackageFormat] = None
    namespace: Optional[PackageNamespace] = None
    package: Optional[PackageName] = None
    versions: Optional[PackageVersionSummaryList] = None
    nextToken: Optional[PaginationToken] = None


class ListPackagesResult(BaseModel):
    packages: Optional[PackageSummaryList] = None
    nextToken: Optional[PaginationToken] = None


class ListRepositoriesResult(BaseModel):
    repositories: Optional[RepositorySummaryList] = None
    nextToken: Optional[PaginationToken] = None


class ListRepositoriesInDomainResult(ListRepositoriesResult):
    pass


class ListTagsForResourceResult(BaseModel):
    tags: Optional[TagList] = None


class PutDomainPermissionsPolicyResult(DeleteDomainPermissionsPolicyResult):
    pass


class PutRepositoryPermissionsPolicyResult(DeleteDomainPermissionsPolicyResult):
    pass


class RepositoryDescription(BaseModel):
    """
    The details of a repository stored in AWS CodeArtifact. A CodeArtifact repository contains a set of package versions, each of which maps to a set of assets. Repositories are polyglot—a single repository can contain packages of any supported type. Each repository exposes endpoints for fetching and publishing packages using tools like the <code>npm</code> CLI, the Maven CLI (<code>mvn</code>), and <code>pip</code>. You can create up to 100 repositories per AWS account.
    """

    name: Optional[RepositoryName] = None
    administratorAccount: Optional[AccountId] = None
    domainName: Optional[DomainName] = None
    domainOwner: Optional[AccountId] = None
    arn: Optional[Arn] = None
    description: Optional[Description] = None
    upstreams: Optional[UpstreamRepositoryInfoList] = None
    externalConnections: Optional[RepositoryExternalConnectionInfoList] = None


class AssociateExternalConnectionResult(BaseModel):
    repository: Optional[RepositoryDescription] = None


class CreateRepositoryResult(AssociateExternalConnectionResult):
    pass


class DeleteRepositoryResult(AssociateExternalConnectionResult):
    pass


class DescribeRepositoryResult(AssociateExternalConnectionResult):
    pass


class DisassociateExternalConnectionResult(AssociateExternalConnectionResult):
    pass


class UpdateRepositoryResult(AssociateExternalConnectionResult):
    pass
