# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2021-12-31T02:58:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, List, Optional

from pydantic import BaseModel, Extra


class String(BaseModel):
    __root__: str


class OverLimit(BaseModel):
    __root__: Any


class MessageNotInflight(OverLimit):
    pass


class ReceiptHandleIsInvalid(OverLimit):
    pass


class TooManyEntriesInBatchRequest(OverLimit):
    pass


class EmptyBatchRequest(OverLimit):
    pass


class BatchEntryIdsNotDistinct(OverLimit):
    pass


class InvalidBatchEntryId(OverLimit):
    pass


class CreateQueueResult(BaseModel):
    """
    Returns the <code>QueueUrl</code> attribute of the created queue.
    """

    QueueUrl: Optional[String] = None


class TagValue(String):
    pass


class QueueDeletedRecently(OverLimit):
    pass


class QueueNameExists(OverLimit):
    pass


class InvalidIdFormat(OverLimit):
    pass


class DeleteMessageBatchRequestEntry(BaseModel):
    """
    Encloses a receipt handle and an identifier for it.
    """

    Id: String
    ReceiptHandle: String


class QueueAttributeName(Enum):
    All = 'All'
    Policy = 'Policy'
    VisibilityTimeout = 'VisibilityTimeout'
    MaximumMessageSize = 'MaximumMessageSize'
    MessageRetentionPeriod = 'MessageRetentionPeriod'
    ApproximateNumberOfMessages = 'ApproximateNumberOfMessages'
    ApproximateNumberOfMessagesNotVisible = 'ApproximateNumberOfMessagesNotVisible'
    CreatedTimestamp = 'CreatedTimestamp'
    LastModifiedTimestamp = 'LastModifiedTimestamp'
    QueueArn = 'QueueArn'
    ApproximateNumberOfMessagesDelayed = 'ApproximateNumberOfMessagesDelayed'
    DelaySeconds = 'DelaySeconds'
    ReceiveMessageWaitTimeSeconds = 'ReceiveMessageWaitTimeSeconds'
    RedrivePolicy = 'RedrivePolicy'
    FifoQueue = 'FifoQueue'
    ContentBasedDeduplication = 'ContentBasedDeduplication'
    KmsMasterKeyId = 'KmsMasterKeyId'
    KmsDataKeyReusePeriodSeconds = 'KmsDataKeyReusePeriodSeconds'
    DeduplicationScope = 'DeduplicationScope'
    FifoThroughputLimit = 'FifoThroughputLimit'
    RedriveAllowPolicy = 'RedriveAllowPolicy'


class InvalidAttributeName(OverLimit):
    pass


class GetQueueUrlResult(CreateQueueResult):
    """
    For more information, see <a href="https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-api-responses.html">Interpreting Responses</a> in the <i>Amazon SQS Developer Guide</i>.
    """

    pass


class QueueDoesNotExist(OverLimit):
    pass


class PurgeQueueInProgress(OverLimit):
    pass


class MessageAttributeName(String):
    pass


class SendMessageResult(BaseModel):
    """
    The <code>MD5OfMessageBody</code> and <code>MessageId</code> elements.
    """

    MD5OfMessageBody: Optional[String] = None
    MD5OfMessageAttributes: Optional[String] = None
    MD5OfMessageSystemAttributes: Optional[String] = None
    MessageId: Optional[String] = None
    SequenceNumber: Optional[String] = None


class InvalidMessageContents(OverLimit):
    pass


class UnsupportedOperation(OverLimit):
    pass


class BatchRequestTooLong(OverLimit):
    pass


class TagKey(String):
    pass


class AWSAccountIdList(BaseModel):
    __root__: List[String]


class ActionNameList(AWSAccountIdList):
    pass


class AddPermissionRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    Label: String
    AWSAccountIds: AWSAccountIdList
    Actions: ActionNameList


class AttributeNameList(BaseModel):
    __root__: List[QueueAttributeName]


class Boolean(BaseModel):
    __root__: bool


class BatchResultErrorEntry(BaseModel):
    """
    Gives a detailed description of the result of an action on each entry in the request.
    """

    Id: String
    SenderFault: Boolean
    Code: String
    Message: Optional[String] = None


class BatchResultErrorEntryList(BaseModel):
    __root__: List[BatchResultErrorEntry]


class Binary(String):
    pass


class BinaryList(BaseModel):
    __root__: List[Binary]


class BoxedInteger(BaseModel):
    __root__: int


class Integer(BoxedInteger):
    pass


class ChangeMessageVisibilityBatchResultEntry(BaseModel):
    """
    Encloses the <code>Id</code> of an entry in <code> <a>ChangeMessageVisibilityBatch</a>.</code>
    """

    Id: String


class ChangeMessageVisibilityRequest(BaseModel):
    QueueUrl: String
    ReceiptHandle: String
    VisibilityTimeout: Integer


class QueueAttributeMap(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class TagMap(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class CreateQueueRequest(BaseModel):
    """
    <p/>
    """

    QueueName: String
    Attributes: Optional[QueueAttributeMap] = None
    tags: Optional[TagMap] = None


class DeleteMessageBatchRequestEntryList(BaseModel):
    __root__: List[DeleteMessageBatchRequestEntry]


class DeleteMessageBatchRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    Entries: DeleteMessageBatchRequestEntryList


class DeleteMessageBatchResultEntry(ChangeMessageVisibilityBatchResultEntry):
    """
    Encloses the <code>Id</code> of an entry in <code> <a>DeleteMessageBatch</a>.</code>
    """

    pass


class DeleteMessageRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    ReceiptHandle: String


class DeleteQueueRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String


class GetQueueAttributesRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    AttributeNames: Optional[AttributeNameList] = None


class GetQueueUrlRequest(BaseModel):
    """
    <p/>
    """

    QueueName: String
    QueueOwnerAWSAccountId: Optional[String] = None


class Token(String):
    pass


class ListDeadLetterSourceQueuesRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    NextToken: Optional[Token] = None
    MaxResults: Optional[BoxedInteger] = None


class QueueUrlList(AWSAccountIdList):
    pass


class ListQueueTagsRequest(BaseModel):
    QueueUrl: String


class ListQueuesRequest(BaseModel):
    """
    <p/>
    """

    QueueNamePrefix: Optional[String] = None
    NextToken: Optional[Token] = None
    MaxResults: Optional[BoxedInteger] = None


class MessageSystemAttributeMap(QueueAttributeMap):
    pass


class MessageBodyAttributeMap(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class Message1(BaseModel):
    """
    An Amazon SQS message.
    """

    MessageId: Optional[String] = None
    ReceiptHandle: Optional[String] = None
    MD5OfBody: Optional[String] = None
    Body: Optional[String] = None
    Attributes: Optional[MessageSystemAttributeMap] = None
    MD5OfMessageAttributes: Optional[String] = None
    MessageAttributes: Optional[MessageBodyAttributeMap] = None


class MessageAttributeNameList(BaseModel):
    __root__: List[MessageAttributeName]


class StringList(AWSAccountIdList):
    pass


class MessageBodySystemAttributeMap(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class MessageList(BaseModel):
    __root__: List[Message1]


class MessageSystemAttributeName(Enum):
    SenderId = 'SenderId'
    SentTimestamp = 'SentTimestamp'
    ApproximateReceiveCount = 'ApproximateReceiveCount'
    ApproximateFirstReceiveTimestamp = 'ApproximateFirstReceiveTimestamp'
    SequenceNumber = 'SequenceNumber'
    MessageDeduplicationId = 'MessageDeduplicationId'
    MessageGroupId = 'MessageGroupId'
    AWSTraceHeader = 'AWSTraceHeader'


class MessageSystemAttributeNameForSends(Enum):
    AWSTraceHeader = 'AWSTraceHeader'


class PurgeQueueRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String


class ReceiveMessageRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    AttributeNames: Optional[AttributeNameList] = None
    MessageAttributeNames: Optional[MessageAttributeNameList] = None
    MaxNumberOfMessages: Optional[Integer] = None
    VisibilityTimeout: Optional[Integer] = None
    WaitTimeSeconds: Optional[Integer] = None
    ReceiveRequestAttemptId: Optional[String] = None


class RemovePermissionRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    Label: String


class SendMessageBatchResultEntry(BaseModel):
    """
    Encloses a <code>MessageId</code> for a successfully-enqueued message in a <code> <a>SendMessageBatch</a>.</code>
    """

    Id: String
    MessageId: String
    MD5OfMessageBody: String
    MD5OfMessageAttributes: Optional[String] = None
    MD5OfMessageSystemAttributes: Optional[String] = None
    SequenceNumber: Optional[String] = None


class SendMessageRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    MessageBody: String
    DelaySeconds: Optional[Integer] = None
    MessageAttributes: Optional[MessageBodyAttributeMap] = None
    MessageSystemAttributes: Optional[MessageBodySystemAttributeMap] = None
    MessageDeduplicationId: Optional[String] = None
    MessageGroupId: Optional[String] = None


class SetQueueAttributesRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    Attributes: QueueAttributeMap


class TagKeyList(BaseModel):
    __root__: List[TagKey]


class TagQueueRequest(BaseModel):
    QueueUrl: String
    Tags: TagMap


class UntagQueueRequest(BaseModel):
    QueueUrl: String
    TagKeys: TagKeyList


class ChangeMessageVisibilityBatchRequestEntry(BaseModel):
    """
    <p>Encloses a receipt handle and an entry id for each message in <code> <a>ChangeMessageVisibilityBatch</a>.</code> </p> <important> <p>All of the following list parameters must be prefixed with <code>ChangeMessageVisibilityBatchRequestEntry.n</code>, where <code>n</code> is an integer value starting with <code>1</code>. For example, a parameter list for this action might look like this:</p> </important> <p> <code>&amp;ChangeMessageVisibilityBatchRequestEntry.1.Id=change_visibility_msg_2</code> </p> <p> <code>&amp;ChangeMessageVisibilityBatchRequestEntry.1.ReceiptHandle=your_receipt_handle</code> </p> <p> <code>&amp;ChangeMessageVisibilityBatchRequestEntry.1.VisibilityTimeout=45</code> </p>
    """

    Id: String
    ReceiptHandle: String
    VisibilityTimeout: Optional[Integer] = None


class GetQueueAttributesResult(BaseModel):
    """
    A list of returned queue attributes.
    """

    Attributes: Optional[QueueAttributeMap] = None


class ListDeadLetterSourceQueuesResult(BaseModel):
    """
    A list of your dead letter source queues.
    """

    queueUrls: QueueUrlList
    NextToken: Optional[Token] = None


class ListQueueTagsResult(BaseModel):
    Tags: Optional[TagMap] = None


class ListQueuesResult(BaseModel):
    """
    A list of your queues.
    """

    QueueUrls: Optional[QueueUrlList] = None
    NextToken: Optional[Token] = None


class ReceiveMessageResult(BaseModel):
    """
    A list of received messages.
    """

    Messages: Optional[MessageList] = None


class MessageAttributeValue(BaseModel):
    """
    <p>The user-specified message attribute value. For string data types, the <code>Value</code> attribute has the same restrictions on the content as the message body. For more information, see <code> <a>SendMessage</a>.</code> </p> <p> <code>Name</code>, <code>type</code>, <code>value</code> and the message body must not be empty or null. All parts of the message attribute, including <code>Name</code>, <code>Type</code>, and <code>Value</code>, are part of the message size restriction (256 KB or 262,144 bytes).</p>
    """

    StringValue: Optional[String] = None
    BinaryValue: Optional[Binary] = None
    StringListValues: Optional[StringList] = None
    BinaryListValues: Optional[BinaryList] = None
    DataType: String


class MessageSystemAttributeValue(MessageAttributeValue):
    """
    <p>The user-specified message system attribute value. For string data types, the <code>Value</code> attribute has the same restrictions on the content as the message body. For more information, see <code> <a>SendMessage</a>.</code> </p> <p> <code>Name</code>, <code>type</code>, <code>value</code> and the message body must not be empty or null.</p>
    """

    pass


class SendMessageBatchRequestEntry(BaseModel):
    """
    Contains the details of a single Amazon SQS message along with an <code>Id</code>.
    """

    Id: String
    MessageBody: String
    DelaySeconds: Optional[Integer] = None
    MessageAttributes: Optional[MessageBodyAttributeMap] = None
    MessageSystemAttributes: Optional[MessageBodySystemAttributeMap] = None
    MessageDeduplicationId: Optional[String] = None
    MessageGroupId: Optional[String] = None


class ChangeMessageVisibilityBatchRequestEntryList(BaseModel):
    __root__: List[ChangeMessageVisibilityBatchRequestEntry]


class ChangeMessageVisibilityBatchRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    Entries: ChangeMessageVisibilityBatchRequestEntryList


class ChangeMessageVisibilityBatchResultEntryList(BaseModel):
    __root__: List[ChangeMessageVisibilityBatchResultEntry]


class DeleteMessageBatchResultEntryList(BaseModel):
    __root__: List[DeleteMessageBatchResultEntry]


class SendMessageBatchRequestEntryList(BaseModel):
    __root__: List[SendMessageBatchRequestEntry]


class SendMessageBatchRequest(BaseModel):
    """
    <p/>
    """

    QueueUrl: String
    Entries: SendMessageBatchRequestEntryList


class SendMessageBatchResultEntryList(BaseModel):
    __root__: List[SendMessageBatchResultEntry]


class ChangeMessageVisibilityBatchResult(BaseModel):
    """
    For each message in the batch, the response contains a <code> <a>ChangeMessageVisibilityBatchResultEntry</a> </code> tag if the message succeeds or a <code> <a>BatchResultErrorEntry</a> </code> tag if the message fails.
    """

    Successful: ChangeMessageVisibilityBatchResultEntryList
    Failed: BatchResultErrorEntryList


class DeleteMessageBatchResult(BaseModel):
    """
    For each message in the batch, the response contains a <code> <a>DeleteMessageBatchResultEntry</a> </code> tag if the message is deleted or a <code> <a>BatchResultErrorEntry</a> </code> tag if the message can't be deleted.
    """

    Successful: DeleteMessageBatchResultEntryList
    Failed: BatchResultErrorEntryList


class SendMessageBatchResult(BaseModel):
    """
    For each message in the batch, the response contains a <code> <a>SendMessageBatchResultEntry</a> </code> tag if the message succeeds or a <code> <a>BatchResultErrorEntry</a> </code> tag if the message fails.
    """

    Successful: SendMessageBatchResultEntryList
    Failed: BatchResultErrorEntryList
